spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: bpi
  password: bpi

camunda.bpm.run.auth.enabled: true

server:
  port: 8080

spring:
  application:
    name: bpicamunda
